name: firebase_dart_ui.example
description: Firebase UI wrapper Example
version: 0.0.12
environment:
  sdk: '>2.0.0 <3.0.0'

dependencies:
  angular:  ^5.0.0
  firebase: ^5.0.1
  firebase_dart_ui:
    path: ../../firebase_dart_ui


dev_dependencies:
  build_runner: ^0.10.1
  build_web_compilers: ^0.4.0

