name: firebase_dart_ui
description: An Angular Dart wrapper for Firebase UI. Demo app at https://dart-ui-demo.firebaseapp.com/
version: 0.1.2
homepage: https://github.com/wstrange/firebase_dart_ui
author: Warren Strange <warren.strange@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular:  ^5.0.0
  firebase: ^6.0.0
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0

